{% set name = "lcopt-cv" %}
{% set dl_name = "lcopt_cv" %}
{% set version = "0.1.3" %}
{% set hash_type = "sha256" %}
{% set hash_value = "4a3f31c823baee7c0239b5c88e3b151bcff02d96d205056dda9d58dee6b4d210" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ dl_name }}/{{ dl_name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt
  entry_points:
    - lcopt-cv = lcopt_cv.bin.lcopt_cv_gui:main
    - lcopt-cv-q = lcopt_cv.bin.lcopt_cv_gui_q:main

requirements:
  build:
    - appdirs
    - asteval
    - brightway2
    - bw2analyzer >=0.9.4
    - bw2calc
    - bw2data
    - bw2io >=0.5.10
    - bw2parameters
    - docopt
    - eight
    - flask
    - future
    - imutils
    - jupyter
    - lxml
    - lcopt
    - numpy
    - pandas
    - peewee >=2.8
    - pillow
    - psutil
    - pypardiso
    - pyprind
    - python
    - pywin32   # [win]
    - requests
    - scipy
    - setuptools
    - stats_arrays
    - unicodecsv
    - voluptuous
    - werkzeug
    - whoosh
    - xlrd
    - xlsxwriter
  run:
    - appdirs
    - asteval
    - brightway2
    - bw2analyzer >=0.9.4
    - bw2calc
    - bw2data
    - bw2io >=0.5.10
    - bw2parameters
    - docopt
    - eight
    - flask
    - future
    - imutils
    - jupyter
    - lxml
    - lcopt
    - numpy
    - pandas
    - peewee >=2.8
    - pillow
    - psutil
    - pypardiso
    - pyprind
    - python
    - pywin32   # [win]
    - requests
    - scipy
    - setuptools
    - stats_arrays
    - unicodecsv
    - voluptuous
    - werkzeug
    - whoosh
    - xlrd
    - xlsxwriter

#test:
#  imports:
#    - {{ name }}

about:
  home: https://github.com/pjamesjoyce/lcopt_cv/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Computer vision module that links to lcopt'
  description: '# lcopt-cv
Computer vision module that links to lcopt

# Installation

`lcopt-cv` requires the `brightway2` and `lcopt` packages to be installed


    Online documentation, including full installation instructions, is available [here](http://lcopt-cv.readthedocs.io)'
  doc_url: 'http://lcopt-cv.readthedocs.io/en/latest/index.html'
  dev_url: 'https://github.com/pjamesjoyce/lcopt_cv'